---
title: "Stat"
author: "Andres Gonzalez"
date: "2022-12-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(skimr)
library(GGally)
library(ggpattern)
library(ggrepel)
library(gt)
library(gtExtras)
library(showtext)
```

```{r}
df <- read_csv("Datasets/life.csv")
```

```{r}
df
glimpse(df)
```
```{r}
font_import()
font_add_google("Roboto slab", family = "roboto-slab")
showtext_auto()
```

```{r}
ggplot(data = df, mapping = aes(x = factor(Year), y = `Life expectancy`)) +
  geom_boxplot() +
  stat_summary(fun.y=mean, geom="point", size=2, color="red") +
  labs(x = "Year",
       title = "Life Expectancy and Year") +
  theme(text = element_text(family = "roboto-slab"),
        plot.title = element_text(size = 14))
```

```{r}
ggplot(df, aes(Status, `Life expectancy`, fill = Status)) + 
  geom_violin() +
  stat_summary(fun.y=mean, geom="point", shape=23, size=2) +
  labs(title = "Life Expectancy and Status") +
  theme(text = element_text(family = "roboto-slab"),
        plot.title = element_text(size = 14))
```


```{r}
df1 <- df %>%
  filter(Year %in% "2014",
         Status %in% "Developing") %>%
  select(-Country,-Year, -Status) %>%
  drop_na()
```

```{r}
ggpairs(subset(df1))
```


```{r}
n = nrow(df1)
mod0 = lm(`Life expectancy` ~ 1, data = df1)
mod.all = lm(`Life expectancy` ~., data = df1)
step(mod0, scope = list(lower = mod0, upper = mod.all))
```

```{r}
mod.full <- lm(`Life expectancy` ~ `Income composition of resources` + 
    `Adult Mortality` + `HIV/AIDS` + `Total expenditure`, data = df1)
summary(mod.full)
```

```{r}
xmat = df1 |>
select(-`Life expectancy`) |>
select_if(is.numeric)
head(xmat)
```

```{r}
dim(xmat)
```

```{r}
library(leaps)
mod = regsubsets(xmat, df1$`Life expectancy`, nvmax = 18)
summary.mod = summary(mod)
names(summary.mod)
```

```{r}
summary.mod$which
```

```{r}
summary.mod$rsq #check R^2
```

```{r}
summary.mod$adjr2 #check adjusted R^2
```

```{r}
plot(summary.mod$adjr2)
```

```{r}
plot(summary.mod$cp) #check Mallows' Cp
abline(1,1)
```

```{r}
summary.mod$cp
```

```{r}
mod.cp = lm(`Life expectancy` ~., data = df1)
summary(mod.cp)
```

```{r}
anova(mod.full,mod.cp)
```


```{r}
add1(mod.full, ~.+`Income composition of resources`*`Adult Mortality`+`Income composition of resources`*`HIV/AIDS`+`Income composition of resources`*`Total expenditure`, test = 'F')
```

```{r}
mod.2 = update(mod.full, ~.+`Income composition of resources`:`Total expenditure`+`Income composition of resources`:`HIV/AIDS`)
summary(mod.2)
```



```{r}
library(broom)
model.table = augment(mod.2)
names(model.table)
ggplot(model.table, aes(x = .fitted, y = .resid)) +
  geom_point() +
  geom_hline(yintercept = 0, colour = 'blue') +
  labs(x = 'Fitted Values', y = 'Residuals') +
  ggtitle('Residual vs Fit') +
  theme_bw()
```

```{r}
ggplot(model.table, aes(sample = .resid)) +
  stat_qq() +
  stat_qq_line() +
  ggtitle('Normal Q-Q Plot') +
  theme_bw()
```

```{r}
shapiro.test(resid(mod.2))
```

```{r}
mod_table = augment(mod.2)
names(mod_table)
```



```{r}
plot(mod.2, which = 4)
```

```{r}
ts = rstudent(mod.2)
which(ts > 3)
```

```{r}
rs = rstandard(mod.2)
which(rs > 3)
```


```{r}
mod.2 %>% augment() %>%
ggplot(., aes(x = .resid)) +
geom_histogram_pattern(pattern_fill = "#2F3C7E",
                       fill = "#FBEAEB",
                       color = "black") +
labs(x = 'Residual') +
ggtitle('Histogram of Residuals') +
theme_bw() +
  theme(text = element_text(family = "roboto-slab"),
        plot.title = element_text(size = 14))
```

Looks normally distributed

### Visualization

```{r}
df1 <- df %>%
  filter(Year %in% "2014",
         Status %in% "Developing") %>%
  drop_na()
```

```{r}
df1 %>%
  arrange(desc(`Life expectancy`)) %>%
  head(10) %>%
  ggplot(aes(x = reorder(Country,-`Life expectancy`), y = `Life expectancy`)) +
  geom_bar_pattern(stat = "identity",
                   pattern_fill = "#F96167",
                   fill = "#FCE77D") +
  geom_text(aes(label=`Life expectancy`), vjust=0, color="black", size=4.5) +
  labs(x = "Countries",
       title = "Highest Countries Life Expectancy in 2014") +
  theme_minimal() +
  theme(text = element_text(family = "roboto-slab"),
        plot.title = element_text(size = 14))
```

```{r}
df1 %>%
  arrange(`Life expectancy`) %>%
  head(10) %>%
  ggplot(aes(x = reorder(Country,`Life expectancy`), y = `Life expectancy`)) +
  geom_bar_pattern(stat = "identity",
                   pattern = "circle",
                   pattern_fill = "#CCF381",
                   fill = "#4831D4") +
  geom_text(aes(label=`Life expectancy`), vjust=0, color="black", size=4.5) +
  labs(x = "Countries",
       title = "Lowest Countries Life Expectancy in 2014") +
  theme_minimal() +
  theme(text = element_text(family = "roboto-slab"),
        plot.title = element_text(size = 14))
```

```{r}
df1 %>% 
  summarize(`Income composition of resources` = mean(`Income composition of resources`),
            LieExp = mean(`Life expectancy`))
```


```{r}
df1 %>%
  ggplot(aes(x = `Income composition of resources`, y = `Life expectancy`, label = Country)) +
geom_point(shape = 21, color = "white", fill = "#ADEFD1FF", size = 2) +
  geom_text_repel(color = "#ADEFD1FF") +
  geom_hline(yintercept = 68.74, color = "#9CC3D5FF", alpha = 0.6, linetype = "dashed") +
  geom_vline(xintercept = 0.64, color = "#9CC3D5FF", alpha = 0.6, linetype = "dashed") +
  annotate("text", family = "Helvetica", fontface = "bold",
           x = 0.235 , y = 70, hjust = 0, alpha = 0.3, color = "#ADEFD1FF",
           label = "Average Life Expetancy") +
  annotate("text", family = "Helvetica", fontface = "bold",
           x = 0.63, y = 60, alpha = 0.3, angle = 90, size = 4, color = "#ADEFD1FF",
           label = "Average Income composition of resources") +
  xlab("Income composition of resources") + ylab("Life Expetancy") +
  labs(title = "Life expectancy and Income composition of resources",
       subtitle = "Developing Countires in 2014") +
  scale_y_continuous(limits = c(40, 80)) +
  ggthemes::theme_solarized_2(light = FALSE, base_family = "Helvetica") +
  theme(panel.background = element_rect(color = "#89CFF0"),
        text = element_text(family = "roboto-slab"),
        plot.title = element_text(size = 18, face = "bold", color = "white"),
        plot.subtitle = element_text(size = 12, color = "#00FFEF"),
        plot.caption = element_text(size = 14, color = "#89CFF0"),
        axis.title = element_text(size = 14, color = "white"),
        axis.text = element_text(size = 12, color = "#89CFF0"),
        panel.grid.minor.x = element_blank()) 
```
```{r}
df1 %>% 
  summarize(`Adult Mortality` = mean(`Adult Mortality`),
            LieExp = mean(`Life expectancy`))
```

```{r}
df1 %>%
  ggplot(aes(x = `Adult Mortality`, y = `Life expectancy`, label = Country)) +
geom_point(shape = 21, color = "white", fill = "#ADEFD1FF", size = 2) +
  geom_text_repel(color = "#ADEFD1FF") +
  geom_hline(yintercept = 68.74, color = "#9CC3D5FF", alpha = 0.6, linetype = "dashed") +
  geom_vline(xintercept = 174.47, color = "#9CC3D5FF", alpha = 0.6, linetype = "dashed") +
  annotate("text", family = "Helvetica", fontface = "bold",
           x = 0.235 , y = 70, hjust = 0, alpha = 0.3, color = "#ADEFD1FF",
           label = "Average Life Expetancy") +
  annotate("text", family = "Helvetica", fontface = "bold",
           x = 168, y = 60, alpha = 0.3, angle = 90, size = 4, color = "#ADEFD1FF",
           label = "Average Adult Mortality") +
  xlab("Adult Mortality") + ylab("Life Expetancy") +
  labs(title = "Life expectancy and Adult Mortality",
       subtitle = "Developing Countires in 2014") +
  scale_y_continuous(limits = c(40, 80)) +
  ggthemes::theme_solarized_2(light = FALSE, base_family = "Helvetica") +
  theme(panel.background = element_rect(color = "#89CFF0"),
        text = element_text(family = "roboto-slab"),
        plot.title = element_text(size = 18, face = "bold", color = "white"),
        plot.subtitle = element_text(size = 12, color = "#00FFEF"),
        plot.caption = element_text(size = 14, color = "#89CFF0"),
        axis.title = element_text(size = 14, color = "white"),
        axis.text = element_text(size = 12, color = "#89CFF0"),
        panel.grid.minor.x = element_blank())
```

```{r}
df1 %>% 
  summarize(`HIV/AIDS` = mean(`HIV/AIDS`),
            LieExp = mean(`Life expectancy`))
```


```{r}
df1 %>%
  ggplot(aes(x = `HIV/AIDS`, y = `Life expectancy`, label = Country)) +
geom_point(shape = 21, color = "white", fill = "#ADEFD1FF", size = 2) +
  geom_text_repel(color = "#ADEFD1FF") +
  geom_hline(yintercept = 68.74, color = "#9CC3D5FF", alpha = 0.6, linetype = "dashed") +
  geom_vline(xintercept = 0.93, color = "#9CC3D5FF", alpha = 0.6, linetype = "dashed") +
  annotate("text", family = "Helvetica", fontface = "bold",
           x = 0.235 , y = 70, hjust = 0, alpha = 0.3, color = "#ADEFD1FF",
           label = "Average Life Expetancy") +
  annotate("text", family = "Helvetica", fontface = "bold",
           x = 0.85, y = 60, alpha = 0.3, angle = 90, size = 4, color = "#ADEFD1FF",
           label = "Average HIV/AIDS") +
  xlab("HIV/AIDS") + ylab("Life Expetancy") +
  labs(title = "Life expectancy and HIV/AIDS",
       subtitle = "Developing Countires in 2014") +
  scale_y_continuous(limits = c(40, 80)) +
  ggthemes::theme_solarized_2(light = FALSE, base_family = "Helvetica") +
  theme(panel.background = element_rect(color = "#89CFF0"),
        text = element_text(family = "roboto-slab"),
        plot.title = element_text(size = 18, face = "bold", color = "white"),
        plot.subtitle = element_text(size = 12, color = "#00FFEF"),
        plot.caption = element_text(size = 14, color = "#89CFF0"),
        axis.title = element_text(size = 14, color = "white"),
        axis.text = element_text(size = 12, color = "#89CFF0"),
        panel.grid.minor.x = element_blank())
```

```{r}
df1 %>% 
  summarize(`Total expenditure` = mean(`Total expenditure`),
            LieExp = mean(`Life expectancy`))
```

```{r}
df1 %>%
  ggplot(aes(x = `Total expenditure`, y = `Life expectancy`, label = Country)) +
geom_point(shape = 21, color = "white", fill = "#ADEFD1FF", size = 2) +
  geom_text_repel(color = "#ADEFD1FF") +
  geom_hline(yintercept = 68.74, color = "#9CC3D5FF", alpha = 0.6, linetype = "dashed") +
  geom_vline(xintercept = 5.82, color = "#9CC3D5FF", alpha = 0.6, linetype = "dashed") +
  annotate("text", family = "Helvetica", fontface = "bold",
           x = 0.235 , y = 70, hjust = 0, alpha = 0.3, color = "#ADEFD1FF",
           label = "Average Life Expetancy") +
  annotate("text", family = "Helvetica", fontface = "bold",
           x = 5.6, y = 60, alpha = 0.3, angle = 90, size = 4, color = "#ADEFD1FF",
           label = "Average Total Expenditure") +
  xlab("Total Expenditure") + ylab("Life Expetancy") +
  labs(title = "Life expectancy and Life Expenditure",
       subtitle = "Developing Countires in 2014") +
  scale_y_continuous(limits = c(40, 80)) +
  ggthemes::theme_solarized_2(light = FALSE, base_family = "Helvetica") +
  theme(panel.background = element_rect(color = "#89CFF0"),
        text = element_text(family = "roboto-slab"),
        plot.title = element_text(size = 18, face = "bold", color = "white"),
        plot.subtitle = element_text(size = 12, color = "#00FFEF"),
        plot.caption = element_text(size = 14, color = "#89CFF0"),
        axis.title = element_text(size = 14, color = "white"),
        axis.text = element_text(size = 12, color = "#89CFF0"),
        panel.grid.minor.x = element_blank())
```

```{r}
df1 %>%
  select(Country, `Life expectancy`,`Adult Mortality`,`HIV/AIDS`,`Income composition of resources`,`Total expenditure`) %>%
  arrange(desc(`Life expectancy`)) %>%
  head(20) %>%
  gt(rowname_col = "Country") %>%
  tab_header(
    title = md("Summary of the **Life Expectancy** of Developing Countries in 2014")) %>%
  tab_source_note(
    source_note = md("The Global Health Observatory (GHO) data repository under World Health Organization (WHO) keeps track of the health status as well as many other related factors for all countries")
  ) %>%
  tab_stubhead(label = md("Countries")) %>%
  opt_table_font(font = google_font("Montserrat"), weight = 600) %>%
  data_color(
    columns = `Life expectancy`,
    fn = scales::col_numeric(
      palette = "viridis",
      domain = c(70, 95)
    )
  ) %>%
  gtsave_extra("lifeExp.png", expand = 10)

```

